# -*- coding: utf-8 -*-
"""
build_forecast_script.py
Writes scripts/forecast_mosdac_rainfall.py using safe Python string construction
to avoid PowerShell parsing issues with special characters.
"""
import os, textwrap

TARGET = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                      "forecast_mosdac_rainfall.py")

LINES = []

def L(s=""):
    LINES.append(s)

L("# -*- coding: utf-8 -*-")
L('"""')
L("forecast_mosdac_rainfall.py (v2: gap-corrected)")
L("================================================")
L("MOSDAC half-hourly rainfall forecasting prototype.")
L("")
L("TEMPORAL-GAP VALIDATION (v2 -- corrected):")
L("  A supervised row at index i is valid ONLY if every timestamp required by")
L("  lag features (up to lag_12), rolling windows (up to 12-step), and")
L("  target horizons (+2, +4, +6 steps = +1h, +2h, +3h) exists at EXACTLY")
L("  30-minute intervals in the real MOSDAC series.")
L("  Validation uses actual timestamp differences, NOT array position.")
L("  pandas .shift() is position-based and silently bridges gaps.")
L("  v1 used .shift() naively: 289 interior gap-contaminated rows leaked through.")
L('"""')
L("")
L("import os, warnings")
L("import numpy as np")
L("import pandas as pd")
L("import matplotlib")
L('matplotlib.use("Agg")')
L("import matplotlib.pyplot as plt")
L("import matplotlib.dates as mdates")
L("from sklearn.ensemble import RandomForestRegressor")
L("from sklearn.metrics import mean_absolute_error, mean_squared_error")
L("")
L("try:")
L("    import xgboost as xgb")
L("    USE_XGB = True")
L('    MODEL_NAME = "XGBoost"')
L("except ImportError:")
L("    USE_XGB = False")
L('    MODEL_NAME = "RandomForest"')
L("")
L('warnings.filterwarnings("ignore")')
L("")
L("BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))")
L('DATA_DIR = os.path.join(BASE_DIR, "data", "mosdac")')
L("OUT_DIR  = BASE_DIR")
L('os.makedirs(os.path.join(OUT_DIR, "outputs"), exist_ok=True)')
L("")
L('PIXEL_CSV    = os.path.join(DATA_DIR, "mumbai_rainfall_30min.csv")')
L('FORECAST_CSV = os.path.join(DATA_DIR, "mosdac_forecast_dataset.csv")')
L('RESULTS_TXT  = os.path.join(OUT_DIR, "outputs", "mosdac_forecast_results.txt")')
L('PRED_CSV     = os.path.join(OUT_DIR, "outputs", "mosdac_forecast_predictions.csv")')
L('EVAL_PNG     = os.path.join(OUT_DIR, "outputs", "mosdac_forecast_evaluation.png")')
L('QC_TXT       = os.path.join(OUT_DIR, "outputs", "mosdac_forecast_data_qc.txt")')
L("")
L('HORIZONS      = {"+1h": 2, "+2h": 4, "+3h": 6}')
L("LAGS          = [1, 2, 3, 4, 6, 8, 12]")
L("ROLL_WINS     = [2, 4, 6, 12]")
L("ROLL_MAX_WINS = [4, 12]")
L("ACCUM_WINS    = [4, 8]")
L("STEP_MIN      = 30")
L('STEP          = np.timedelta64(STEP_MIN, "m")')
L("")
L('C_ACTUAL  = "#1F497D"')
L('C_PERSIST = "#E67E22"')
L('C_ML      = "#27AE60"')
L("")
L("# v1 results for comparison table")
L("V1 = {")
L('    "+1h": {"pm":0.6166,"pr":2.6078,"pr2":-0.3364,"mm":0.3964,"mr":1.8974,"mr2":0.2926},')
L('    "+2h": {"pm":0.7159,"pr":2.7337,"pr2":-0.4692,"mm":0.4774,"mr":2.1179,"mr2":0.1181},')
L('    "+3h": {"pm":0.7575,"pr":2.9050,"pr2":-0.6576,"mm":0.5507,"mr":2.2855,"mr2":-0.0260},')
L("}")
L("")
L("# =============================================================================")
L("# STEP 1 -- Load pixel data and build regional mean series")
L("# =============================================================================")
L('print("Loading MOSDAC pixel data...")')
L('raw = pd.read_csv(PIXEL_CSV)')
L('raw["timestamp"] = pd.to_datetime(raw["timestamp"])')
L('rain_col = "rainfall_mm_hr"')
L("")
L('ts_sorted_all = np.sort(raw["timestamp"].unique())')
L('full_range    = pd.date_range(ts_sorted_all[0], ts_sorted_all[-1], freq="30min")')
L('missing_ts    = sorted(set(full_range) - set(pd.DatetimeIndex(ts_sorted_all)))')
L('ppt           = raw.groupby("timestamp").size()')
L('dupes         = raw.duplicated(subset=["timestamp","latitude","longitude"]).sum()')
L('zero_frac     = (raw[rain_col] == 0).mean()')
L('ts_means_all  = raw.groupby("timestamp")[rain_col].mean()')
L("")
L("ts_series = (raw.groupby(\"timestamp\")[rain_col]")
L('             .mean().rename("rainfall_mumbai_mean_mmhr")')
L("             .sort_index().reset_index())")
L('ts_series.columns = ["timestamp", "rainfall_mumbai_mean_mmhr"]')
L('r = "rainfall_mumbai_mean_mmhr"')
L("")
L('ts_arr = ts_series["timestamp"].values')
L("vals   = ts_series[r].values")
L("n      = len(ts_arr)")
L('print("  Regional mean series: %d timesteps" % n)')
L("")
L("# =============================================================================")
L("# STEP 2 -- Strict temporal-gap validation")
L("# =============================================================================")
L('print("Computing strict gap-validity mask...")')
L("")
L("valid_mask = np.zeros(n, dtype=bool)")
L("drop_lag = drop_tgt = drop_oob = 0")
L("")
L("for i in range(n):")
L("    ok = True")
L("    for k in LAGS:")
L("        if i - k < 0:")
L("            ok = False; drop_oob += 1; break")
L('        diff = int((ts_arr[i] - ts_arr[i-k]) / np.timedelta64(1, "m"))')
L("        if diff != k * STEP_MIN:")
L("            ok = False; drop_lag += 1; break")
L("    if ok:")
L("        for s in HORIZONS.values():")
L("            if i + s >= n:")
L("                ok = False; drop_oob += 1; break")
L('            diff = int((ts_arr[i+s] - ts_arr[i]) / np.timedelta64(1, "m"))')
L("            if diff != s * STEP_MIN:")
L("                ok = False; drop_tgt += 1; break")
L("    valid_mask[i] = ok")
L("")
L("n_valid   = int(valid_mask.sum())")
L("n_dropped = n - n_valid")
L("n_old_valid = 651")
L("n_leaked    = n_dropped - (n - n_old_valid)")
L("")
L('print("  Total rows     : %d" % n)')
L('print("  Valid rows     : %d" % n_valid)')
L('print("  Dropped total  : %d" % n_dropped)')
L('print("    out-of-bounds: %d" % drop_oob)')
L('print("    lag gap      : %d" % drop_lag)')
L('print("    target gap   : %d" % drop_tgt)')
L('print("  v1 valid rows (leaked): %d" % n_old_valid)')
L('print("  Interior rows leaked in v1: %d" % n_leaked)')
L("")
L("# =============================================================================")
L("# STEP 3 -- Feature engineering (gap-safe, direct index access)")
L("# =============================================================================")
L('print("\\nEngineering features on valid rows...")')
L("valid_idx = np.where(valid_mask)[0]")
L("rows = []")
L("for i in valid_idx:")
L("    row = {\"timestamp\": ts_arr[i], r: vals[i]}")
L("    for k in LAGS:")
L('        row["lag_%d" % k] = vals[i - k]')
L("    for w in ROLL_WINS:")
L('        row["roll_mean_%d" % w] = float(np.mean(vals[i-w:i]))')
L("    for w in ROLL_MAX_WINS:")
L('        row["roll_max_%d" % w] = float(np.max(vals[i-w:i]))')
L('    row["delta_1"] = vals[i] - vals[i-1]')
L('    row["delta_2"] = vals[i] - vals[i-2]')
L("    for w in ACCUM_WINS:")
L('        row["accum_%dstep" % w] = float(np.sum(vals[i-w:i]) * 0.5)')
L("    ts_pd = pd.Timestamp(ts_arr[i])")
L('    row["hour_sin"] = np.sin(2 * np.pi * ts_pd.hour / 24)')
L('    row["hour_cos"] = np.cos(2 * np.pi * ts_pd.hour / 24)')
L("    for label, s in HORIZONS.items():")
L('        row["target_%s" % label] = vals[i + s]')
L("    rows.append(row)")
L("")
L("feat_clean   = pd.DataFrame(rows).reset_index(drop=True)")
L('TARGET_COLS  = ["target_%s" % h for h in HORIZONS]')
L('FEATURE_COLS = [c for c in feat_clean.columns if c != "timestamp" and c not in TARGET_COLS]')
L("")
L("assert feat_clean[FEATURE_COLS + TARGET_COLS].isna().sum().sum() == 0, \\")
L('    "NaN detected after gap-validation -- logic error!"')
L('print("  Clean rows : %d" % len(feat_clean))')
L('print("  Features   : %d" % len(FEATURE_COLS))')
L('print("  NaN check  : PASSED")')
L("")
L('feat_clean[["timestamp"] + FEATURE_COLS + TARGET_COLS].to_csv(FORECAST_CSV, index=False)')
L('print("  Forecast dataset -> %s" % FORECAST_CSV)')
L("")
L("# =============================================================================")
L("# STEP 4 -- Chronological 60/20/20 split")
L("# =============================================================================")
L("nf = len(feat_clean)")
L("train_end = int(nf * 0.60)")
L("val_end   = int(nf * 0.80)")
L("df_train = feat_clean.iloc[:train_end].copy()")
L("df_val   = feat_clean.iloc[train_end:val_end].copy()")
L("df_test  = feat_clean.iloc[val_end:].copy()")
L("")
L('print("\\nChronological split:")')
L('print("  Train : %4d rows  %s -> %s" % (len(df_train),')
L('      str(df_train.timestamp.min())[:19], str(df_train.timestamp.max())[:19]))')
L('print("  Val   : %4d rows  %s -> %s" % (len(df_val),')
L('      str(df_val.timestamp.min())[:19], str(df_val.timestamp.max())[:19]))')
L('print("  Test  : %4d rows  %s -> %s" % (len(df_test),')
L('      str(df_test.timestamp.min())[:19], str(df_test.timestamp.max())[:19]))')
L("")
L("X_train = df_train[FEATURE_COLS].values")
L("X_val   = df_val[FEATURE_COLS].values")
L("X_test  = df_test[FEATURE_COLS].values")
L("")
L("# =============================================================================")
L("# STEP 5 -- Persistence baseline and XGBoost model")
L("# =============================================================================")
L("def metrics(y_true, y_pred, label):")
L("    mae  = mean_absolute_error(y_true, y_pred)")
L("    rmse = float(np.sqrt(mean_squared_error(y_true, y_pred)))")
L("    denom = float(np.sum((y_true - y_true.mean())**2))")
L("    r2 = 1.0 - float(np.sum((y_true - y_pred)**2)) / denom if denom > 0 else float(\"nan\")")
L("    return {\"label\":label, \"MAE\":mae, \"RMSE\":rmse, \"R2\":r2, \"n\":len(y_true)}")
L("")
L("results   = {}")
L("preds_all = {}")
L("")
L("for horizon, steps in HORIZONS.items():")
L('    tc = "target_%s" % horizon')
L("    y_train = df_train[tc].values")
L("    y_val   = df_val[tc].values")
L("    y_test  = df_test[tc].values")
L("    persist_val  = np.clip(df_val[r].values,  0, None)")
L("    persist_test = np.clip(df_test[r].values, 0, None)")
L("")
L("    if USE_XGB:")
L("        dtrain = xgb.DMatrix(X_train, label=y_train)")
L("        dval_m = xgb.DMatrix(X_val,   label=y_val)")
L("        dtest  = xgb.DMatrix(X_test,  label=y_test)")
L("        params = {\"objective\":\"reg:squarederror\",\"max_depth\":4,\"learning_rate\":0.05,")
L("                  \"subsample\":0.8,\"colsample_bytree\":0.8,\"min_child_weight\":5,")
L("                  \"eval_metric\":\"rmse\",\"verbosity\":0,\"seed\":42}")
L("        model = xgb.train(params, dtrain, num_boost_round=500,")
L("                          evals=[(dtrain,\"train\"),(dval_m,\"val\")],")
L("                          early_stopping_rounds=30, verbose_eval=False)")
L("        ml_val_pred  = np.clip(model.predict(dval_m), 0, None)")
L("        ml_test_pred = np.clip(model.predict(dtest),  0, None)")
L("    else:")
L("        model = RandomForestRegressor(n_estimators=200, max_depth=6,")
L("                                      min_samples_leaf=5, random_state=42, n_jobs=-1)")
L("        model.fit(X_train, y_train)")
L("        ml_val_pred  = np.clip(model.predict(X_val),  0, None)")
L("        ml_test_pred = np.clip(model.predict(X_test), 0, None)")
L("")
L("    results[horizon] = {")
L('        "persistence_val":  metrics(y_val,  persist_val,  "Persistence %s [val]" % horizon),')
L('        "persistence_test": metrics(y_test, persist_test, "Persistence %s [test]" % horizon),')
L('        "ml_val":           metrics(y_val,  ml_val_pred,  "%s %s [val]" % (MODEL_NAME, horizon)),')
L('        "ml_test":          metrics(y_test, ml_test_pred, "%s %s [test]" % (MODEL_NAME, horizon)),')
L("    }")
L("    preds_all[horizon] = {")
L('        "timestamps":    df_test["timestamp"].values,')
L('        "y_actual":      y_test,')
L('        "y_persistence": persist_test,')
L('        "y_ml":          ml_test_pred,')
L("    }")
L('    print("\\n%s:" % horizon)')
L("    for v in results[horizon].values():")
L('        print("  %-45s  MAE=%.4f  RMSE=%.4f  R2=%.4f" % (')
L('              v["label"], v["MAE"], v["RMSE"], v["R2"]))')
L("")
L("# =============================================================================")
L("# STEP 6 -- Evaluation plot")
L("# =============================================================================")
L('print("\\nGenerating evaluation plot...")')
L("fig, axes = plt.subplots(3, 1, figsize=(15, 12), facecolor=\"white\", sharex=False)")
L('title_line1 = "MOSDAC Half-Hourly Rainfall Forecast Evaluation -- Test Set (v2: gap-corrected)"')
L('title_line2 = "(INSAT-3DS HEM, 8-22 Sep 2026, %s vs Persistence)" % MODEL_NAME')
L('title_line3 = "WARNING: 15-day prototype only. Results NOT generalisable to operational use."')
L('fig.suptitle(title_line1 + "\\n" + title_line2 + "\\n" + title_line3,')
L('             fontsize=11, fontweight="bold", color="#1B2A41")')
L("")
L("for ax, (horizon, pd_) in zip(axes, preds_all.items()):")
L('    ts = pd.DatetimeIndex(pd_["timestamps"])')
L('    ax.set_facecolor("#F7F9FC")')
L('    ax.grid(color="#C8D4E3", linewidth=0.5, linestyle="--")')
L('    ax.spines[["top","right"]].set_visible(False)')
L('    ax.plot(ts, pd_["y_actual"],      color=C_ACTUAL,  linewidth=1.2, label="Actual", zorder=3)')
L('    ax.plot(ts, pd_["y_persistence"], color=C_PERSIST, linewidth=1.0,')
L('            alpha=0.8, linestyle="--", label="Persistence", zorder=2)')
L('    ax.plot(ts, pd_["y_ml"],          color=C_ML,      linewidth=1.0,')
L('            alpha=0.8, linestyle="-.", label=MODEL_NAME, zorder=2)')
L('    r_p = results[horizon]["persistence_test"]')
L('    r_m = results[horizon]["ml_test"]')
L('    improved = r_m["MAE"] < r_p["MAE"]')
L('    verdict  = "ML < Persistence" if improved else "ML >= Persistence"')
L('    info = ("Horizon %s  |  n=%d (gap-corrected)\\n"')
L('            "Persistence: MAE=%.3f  RMSE=%.3f  R2=%.3f\\n"')
L('            "%s:  MAE=%.3f  RMSE=%.3f  R2=%.3f\\n"')
L('            "Verdict: %s") % (horizon, r_p["n"], r_p["MAE"], r_p["RMSE"], r_p["R2"],')
L('                               MODEL_NAME, r_m["MAE"], r_m["RMSE"], r_m["R2"], verdict)')
L('    ax.text(0.01, 0.97, info, transform=ax.transAxes, fontsize=8, va="top", ha="left",')
L('            color="#1B2A41", bbox=dict(boxstyle="round,pad=0.4", fc="white", ec="#C8D4E3", alpha=0.92))')
L('    ax.set_ylabel("Rainfall rate (mm/hr)", fontsize=9)')
L('    ax.set_title("Horizon %s  (v2: gap-corrected)" % horizon,')
L('                 fontsize=10, fontweight="bold", color="#1B2A41")')
L('    ax.legend(fontsize=8, loc="upper right")')
L('    ax.xaxis.set_major_formatter(mdates.DateFormatter("%d %b %H:%M"))')
L("    ax.xaxis.set_major_locator(mdates.HourLocator(interval=6))")
L('    plt.setp(ax.xaxis.get_majorticklabels(), rotation=25, ha="right", fontsize=7)')
L("")
L("fig.tight_layout(h_pad=2.5)")
L('fig.savefig(EVAL_PNG, dpi=150, bbox_inches="tight", facecolor="white")')
L("plt.close(fig)")
L('print("  Saved -> %s" % EVAL_PNG)')
L("")
L("# =============================================================================")
L("# STEP 7 -- Predictions CSV")
L("# =============================================================================")
L("pred_rows = []")
L("for horizon, pd_ in preds_all.items():")
L("    for i, ts in enumerate(pd_[\"timestamps\"]):")
L('        pred_rows.append({"timestamp":str(ts),"horizon":horizon,')
L('                          "actual_mmhr":pd_["y_actual"][i],')
L('                          "persistence_mmhr":pd_["y_persistence"][i],')
L('                          "ml_mmhr":pd_["y_ml"][i]})')
L("pd.DataFrame(pred_rows).to_csv(PRED_CSV, index=False)")
L('print("  Predictions -> %s" % PRED_CSV)')
L("")
L("# =============================================================================")
L("# Results report")
L("# =============================================================================")
L("rl = [")
L('    "=" * 68,')
L('    "MOSDAC RAINFALL FORECAST -- FINAL RESULTS REPORT (v2: gap-corrected)",')
L('    "Model: %s" % MODEL_NAME,')
L('    "=" * 68,')
L('    "",')
L('    "1. MOSDAC OBSERVATION COUNT",')
L('    "   Total pixel observations  : %d" % len(raw),')
L('    "   Unique timestamps         : %d" % len(ts_sorted_all),')
L('    "   Spatial pixels/timestamp  : 153 (constant)",')
L('    "   Archive start             : %s" % raw.timestamp.min(),')
L('    "   Archive end               : %s" % raw.timestamp.max(),')
L('    "",')
L('    "2. DATE/TIME COVERAGE",')
L('    "   Nominal: 2026-09-08 00:00 to 2026-09-22 13:30 UTC",')
L('    "   Actual: %d of %d expected 30-min slots" % (len(ts_sorted_all), len(full_range)),')
L('    "",')
L('    "3. MISSING TIMESTAMPS",')
L('    "   Count   : %d" % len(missing_ts),')
L('    "   Pattern : 17:30 and 19:00 UTC systematically absent from 09-Sep onwards.",')
L('    "   Action  : Rows whose feature/target window crosses a gap are excluded (not imputed).",')
L('    "",')
L('    "4. SPATIAL PIXELS",')
L('    "   Per timestamp: 153 (constant)",')
L('    "   Lat: %.3f - %.3f N" % (raw.latitude.min(), raw.latitude.max()),')
L('    "   Lon: %.3f - %.3f E" % (raw.longitude.min(), raw.longitude.max()),')
L('    "",')
L('    "5. FEATURES",')
L('    "   Count: %d" % len(FEATURE_COLS),')
L('    "   List : %s" % str(FEATURE_COLS),')
L('    "",')
L('    "6. TEMPORAL-GAP VALIDATION (v2 correction)",')
L('    "   Validation: actual timestamp differences, NOT array position.",')
L('    "   Row valid only if ts[i]-ts[i-k]==k*30min for all lags k,",')
L('    "   AND ts[i+s]-ts[i]==s*30min for all target steps s.",')
L('    "   Total rows in series      : %d" % n,')
L('    "   Valid rows (gap-free)     : %d" % n_valid,')
L('    "   Dropped (total)           : %d" % n_dropped,')
L('    "     out-of-bounds           : %d" % drop_oob,')
L('    "     lag gap                 : %d" % drop_lag,')
L('    "     target gap              : %d" % drop_tgt,')
L('    "   v1 valid rows (used shift): %d" % n_old_valid,')
L('    "   Interior rows leaked in v1: %d" % n_leaked,')
L('    "",')
L('    "7. DATASET SPLIT (chronological, no shuffling)",')
L('    "   Total clean rows  : %d" % nf,')
L('    "   Train (60%%)      : %d rows  %s - %s" % (len(df_train),')
L('        str(df_train.timestamp.min())[:19], str(df_train.timestamp.max())[:19]),')
L('    "   Validation (20%%): %d rows  %s - %s" % (len(df_val),')
L('        str(df_val.timestamp.min())[:19], str(df_val.timestamp.max())[:19]),')
L('    "   Test (20%%)       : %d rows  %s - %s" % (len(df_test),')
L('        str(df_test.timestamp.min())[:19], str(df_test.timestamp.max())[:19]),')
L('    "",')
L('    "8. PERSISTENCE BASELINE -- TEST SET",')
L("]")
L("for h in HORIZONS:")
L('    p = results[h]["persistence_test"]')
L('    rl.append("   %s:  MAE=%.4f  RMSE=%.4f  R2=%.4f  (n=%d)" % (h,p["MAE"],p["RMSE"],p["R2"],p["n"]))')
L("")
L('rl += ["", "9. %s -- TEST SET" % MODEL_NAME]')
L("for h in HORIZONS:")
L('    m = results[h]["ml_test"]')
L('    rl.append("   %s:  MAE=%.4f  RMSE=%.4f  R2=%.4f  (n=%d)" % (h,m["MAE"],m["RMSE"],m["R2"],m["n"]))')
L("")
L('rl += ["", "10. ML vs PERSISTENCE VERDICT (TEST SET, by MAE)"]')
L("for h in HORIZONS:")
L('    p = results[h]["persistence_test"]')
L('    m = results[h]["ml_test"]')
L('    improved = m["MAE"] < p["MAE"]')
L('    diff_pct = (p["MAE"] - m["MAE"]) / p["MAE"] * 100 if p["MAE"] > 0 else 0.0')
L('    verdict = ("ML IMPROVES over persistence by %.1f%% MAE reduction" % diff_pct')
L('               if improved else')
L('               "ML does NOT improve over persistence (MAE diff: %.1f%%)" % diff_pct)')
L('    rl.append("   %s: %s" % (h, verdict))')
L("")
L('rl += ["",')
L('    "11. COMPARISON: v1 (leaked) vs v2 (gap-corrected) -- TEST SET, MAE",')
L('    "    Horizon   Persist-v1  Persist-v2  Delta     ML-v1   ML-v2   Delta",')
L("]")
L("for h in HORIZONS:")
L('    p1 = V1[h]["pm"]; p2 = results[h]["persistence_test"]["MAE"]')
L('    m1 = V1[h]["mm"]; m2 = results[h]["ml_test"]["MAE"]')
L('    rl.append("    %s        %6.4f      %6.4f  %+.4f    %6.4f  %6.4f  %+.4f" % (')
L("        h, p1, p2, p2-p1, m1, m2, m2-m1))")
L("")
L('rl += [')
L('    "",')
L('    "12. IMPORTANT LIMITATIONS",')
L('    "    * PROTOTYPE: ~15 days only (669 timestamps). NOT operationally generalisable.",')
L('    "    * High zero-rainfall fraction (94.3% of pixels).",')
L('    "    * Rainfall RATE (mm/hr) is forecast, not accumulated rainfall.",')
L('    "    * MOSDAC HEM is satellite-retrieved, not gauge-corrected.",')
L('    "    * 31 missing timestamps. 289 rows that leaked into v1 now correctly excluded.",')
L('    "    * Spatial pixels aggregated to regional mean; sub-pixel variation not modelled.",')
L('    "    * Historical IMD daily rainfall NOT used as training data.",')
L('    "    * This model predicts RAINFALL only. It does NOT predict floods.",')
L('    "",')
L('    "13. FILES CREATED",')
L('    "    data/mosdac/mosdac_forecast_dataset.csv",')
L('    "    outputs/mosdac_forecast_data_qc.txt",')
L('    "    outputs/mosdac_forecast_results.txt",')
L('    "    outputs/mosdac_forecast_predictions.csv",')
L('    "    outputs/mosdac_forecast_evaluation.png",')
L('    "",')
L('    "=" * 68,')
L('    "Generated by: scripts/forecast_mosdac_rainfall.py (v2: gap-corrected)",')
L('    "=" * 68,')
L("]")
L('with open(RESULTS_TXT, "w", encoding="utf-8") as f:')
L('    f.write("\\n".join(rl))')
L('print("  Results -> %s" % RESULTS_TXT)')
L("")
L("# QC report")
L("qcl = [")
L('    "=" * 68,')
L('    "MOSDAC FORECAST DATA QC REPORT (v2: gap-corrected)",',)
L('    "Source: data/mosdac/mumbai_rainfall_30min.csv",')
L('    "=" * 68,')
L('    "",')
L('    "RAW PIXEL DATA",')
L('    "  Total rows             : %d" % len(raw),')
L('    "  Earliest timestamp     : %s" % raw.timestamp.min(),')
L('    "  Latest  timestamp      : %s" % raw.timestamp.max(),')
L('    "  Unique timestamps      : %d" % len(ts_sorted_all),')
L('    "  Expected 30-min slots  : %d" % len(full_range),')
L('    "  Missing timestamps     : %d" % len(missing_ts),')
L('    "  Duplicate pixel rows   : %d" % int(dupes),')
L('    "  Pixels per timestamp   : %d (constant)" % ppt.min(),')
L('    "",')
L('    "MISSING TIMESTAMP LIST",')
L("]")
L("for mt in missing_ts:")
L('    qcl.append("  %s" % mt)')
L('qcl += [')
L('    "",')
L('    "  17:30 and 19:00 UTC systematically absent from 09-Sep-2026.",')
L('    "  Not imputed. Rows needing these are excluded from supervised dataset.",')
L('    "",')
L('    "RAINFALL_MM_HR STATISTICS (pixel level)",')
L('    "  Mean %.4f  Median %.4f  Std %.4f" % (',)
L('        raw[rain_col].mean(), raw[rain_col].median(), raw[rain_col].std()),')
L('    "  Min  %.4f  Max   %.4f" % (raw[rain_col].min(), raw[rain_col].max()),')
L('    "  Zero%%: %.1f%%  NaN: %d  Negative: %d" % (',)
L('        zero_frac*100, raw[rain_col].isna().sum(), (raw[rain_col]<0).sum()),')
L('    "",')
L('    "TEMPORAL-GAP VALIDATION SUMMARY",')
L('    "  Total rows          : %d" % n,')
L('    "  Valid (gap-free)    : %d" % n_valid,')
L('    "  Dropped             : %d" % n_dropped,')
L('    "    out-of-bounds     : %d" % drop_oob,')
L('    "    lag gap           : %d" % drop_lag,')
L('    "    target gap        : %d" % drop_tgt,')
L('    "  v1 leaked rows      : %d" % n_leaked,')
L('    "",')
L('    "UNIT: rainfall_mm_hr is INSAT-3DS HEM rainfall RATE in mm/hr.",')
L('    "Targets are future RATES, NOT accumulated rainfall.",')
L('    "",')
L('    "=" * 68,')
L("]")
L('with open(QC_TXT, "w", encoding="utf-8") as f:')
L('    f.write("\\n".join(qcl))')
L('print("  QC -> %s" % QC_TXT)')
L('print("\\nDone.")')

content = "\n".join(LINES) + "\n"
with open(TARGET, "w", encoding="utf-8") as f:
    f.write(content)
print("Written %s (%d bytes)" % (TARGET, len(content)))
